---
title: "Data Frofilling Report"
author: ""
date: "`r format(lubridate::today(), '%d %b %Y')`"
output: html_document

params:
  dpath: !R data/boston.csv
  target_name: !R target
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# find the root directory for the project and set that as wd
root_dir <- rprojroot::find_root(rprojroot::is_rstudio_project)
knitr::opts_knit$set(root.dir = root_dir)
```

## Overview

The notebook aims to:

1. Import data and load libraries
2. Generate a prescriptive EDA repot


## Load libraries

```{r load, message=FALSE, warning=FALSE}
library(skimr)          # summary stats
library(DataExplorer)   # variable profiling, EDA
library(tidyverse)      # data manipulation
library(tidymodels)     # modelling
library(highcharter)    # interactive visualization
library(janitor)        # clean column names, convert to snake case
```

## Import data

```{r import, message=FALSE, warning=FALSE}
dat <- read_csv(params$dpath) %>%
  rename(target = params$target_name) %>%
  clean_names()
dim(dat)
```


## Summary statistics

```{r summary_stats, message=FALSE, warning=FALSE}
dat %>% skim_to_wide() %>% kable()
```

## Univariate Plots

```{r univariate, fig.height=10, fig.width=14, message=FALSE, warning=FALSE}
plot_boxplot(dat, by = "target")
plot_scatterplot(dat, by = "target")
```

## Correlation Heatmap

```{r correlation, fig.height=10, fig.width=14, message=FALSE, warning=FALSE}
dat %>%
  select_if(rlang::is_bare_numeric) %>%
  cor() %>%
  GnT::hchart_cor()
```
