---
title: "What's the price of a house?"
subtitle: Boston house price prediction using tidymodels
---


- Create prescriptive profiling data report
- Check on data quality
- Build predictive models using tidymodels 
- Compare performance across models


Variable  | Description
------------- | -------------
CRIM  |   per capita crime rate by town
ZN    |   proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS |   proportion of non-retail business acres per town
CHAS  |   Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
NOX   |   nitric oxides concentration (parts per 10 million)
RM    |   average number of rooms per dwelling
AGE   |   proportion of owner-occupied units built prior to 1940
DIS   |   weighted distances to five Boston employment centres
RAD   |   index of accessibility to radial highways
TAX   |   full-value property-tax rate per $10,000
PTRATIO |  pupil-teacher ratio by town
B       | 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT   | % lower status of the population
target  | Median value of owner-occupied homes in $1000's, MEDV originally

